### PR TITLE
SCREAM: fix compilation error on CUDA

### PR DESCRIPTION
**Pull request by bartgol**
#1411 (merged ~4h ago) introduced a cmake bug for our v1 build on CUDA.

The `-Xcudafe xyz` flag for the `scream_control` lib was PUBLIC, and not language specific, so when linking control to the `atm` lib, it caused F90 compilation errors.

### CODE REVIEW

**Comment by tcclevenger** [comment]
This is great to see. I've been debugging this error for the past few hours...

**Review by tcclevenger — APPROVED** [review]

**Comment by bartgol** [comment]
Note: the mappy failure is due to #1411 , which introduced non BFB diffs in the vert coordinates. I ran master CIME tests on mappy, and launcher the bless job. Now the baselines should be up to date, and we can retest this PR.

**Comment by bartgol** [comment]
This fails on mappy just b/c of spa_main (which is a separate issue, already being tackled elsewhere). Merging.
